

<!--//Affichage html-->
<!--accée de l'auteur-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
<head>
		<meta charset="UTF-8">
		<meta name="description" content="Interiart - Le design de votre intérieur à la carte par un décorateur pro">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Blog</title>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
		<link rel="stylesheet" href="css/style.css">
</head>

  <body>
    <div>
    <form action="" method="POST">
      <fieldset>
        <legend>Inscrivez-vous</legend>
       <div> 
       
          <label for="prenom">Prénom :</label> 
          <input type="text" name="firstname" id="firstname" value="" />
        </div>
        <div> 
          <label for="login">Nom :</label> 
          <input type="text" name="lastname" id="lastname" value="" />
        </div>
        <div>
            <label for="mail">e-mail:</label>
            <input type="email" id="mail" name="mail">
        </div>
        
        <div>
          <label for="password">Mot de passe :</label> 
          <input type="password" name="password" id="password" value="" /> 
          
        </div>
      
          <h3 style="color: red"><?php echo $message ?></h3>
       
        <div>
            <input type="submit" name="submit" value="S'authentifier" />
        </div>
      </fieldset>
    </form>
    </div>
  </body>
</html>